import { useState, useEffect, useRef } from "react";
const C={bg:"#080808",surface:"#111111",card:"#161616",warm:"#1c1a18",cream:"#F5F0E8",creamLight:"#FAF8F3",green:"#CCFF00",pink:"#E6007E",pinkPastel:"#FF7EB3",white:"#FFFFFF",textLight:"#d4d0ca",gray:"#999999",dim:"#555555",dimmer:"#2a2a2a",dk:"#1a1a1a",mid:"#3a3a3a",soft:"#666666"};

const T={es:{nav:"Hablemos",tag:"ESTUDIO CREATIVO · MIAMI",h1a:"Tu marca tiene una",h1b:"historia increíble.",h1c:"Vamos a",h1d:"contarla.",sub:"Contenido con intención, estrategia y estética para marcas que quieren conectar. Social media, publicidad digital y branding — todo desde Miami.",cta:"Agendar llamada →",disc:"Sin compromiso, solo conversar.",s1:"+10",s1l:"años de experiencia",s2:"3",s2l:"servicios integrados",s3:"∞",s3l:"compromiso con tu marca",
imgTag:"IMAGINA ESTO ✦",img1:"Tu feed se ve profesional, coherente, con personalidad desde el primer scroll.",img2:"Cada pieza de contenido cuenta algo — y la gente se detiene a mirar.",img3:"Tus clientes te dicen: \"te encontré en redes y supe que eras la indicada.\"",img4:"No tienes que pensar qué publicar cada semana. Ya está resuelto.",img5:"Tu presencia digital refleja, por fin, todo lo que estás construyendo.",
svcTag:"LO QUE HACEMOS",svcH:"Tres formas de hacer",svcHi:"visible",svcH2:"lo que haces",
sm:"Social Media",smD:"Contenido que conecta, con estrategia detrás.",smP:"Creamos y gestionamos el contenido de tus redes de principio a fin. Desde la estrategia hasta la publicación — con producción profesional y dirección creativa.",smI:"Estrategia · Calendario editorial · Content day · Dirección creativa · Guión · Edición · Gestión · Publicación · Reporte mensual",smFrom:"DESDE",perMo:"/mes",
ad:"Publicidad Digital",adD:"Tu inversión, trabajando con estrategia.",adP:"Gestionamos tus campañas en Meta y Google para que cada peso invertido genere resultados reales. Estrategia, configuración técnica, creativos y optimización con datos.",adI:"Estrategia · Configuración técnica · Pixel y eventos · Creativos · Gestión · Optimización · Reporte y análisis",adN1:"Hasta $2,000 en pauta",adN2:"+$2,000 en pauta",adOfSpend:"de la inversión",adNote:"La pauta se paga directo a la plataforma.",
br:"Branding",brD:"La base de todo.",brP:"Construimos la identidad visual y verbal de tu marca. Desde el logo hasta el tono de voz — para que te reconozcan, te recuerden y confíen desde el primer contacto.",brI:"Estrategia de marca · Logo · Identidad visual · Paleta · Tipografía · Tono de voz · Manual de marca · Perfiles para redes",
procTag:"EL CAMINO JUNTOS",procH:"4 pasos para",procHi:"encender",procH2:"lo que construyes",p1:"Conversamos",p1d:"Nos cuentas tu visión. Entendemos lo que haces, tu audiencia y tus metas.",p2:"Diseñamos juntos",p2d:"Co-creamos la estrategia y el plan de contenido alineado a tus objetivos.",p3:"Producimos",p3d:"Un día completo de producción donde grabamos y fotografiamos todo el contenido del mes.",p4:"Gestionamos y medimos",p4d:"Editamos, publicamos, gestionamos tus redes y te entregamos un reporte mensual.",
ptiTag:"ESTO ES PARA TI SI... ✦",pti1:"Tienes un proyecto que ya funciona y quieres que tu presencia digital esté a la altura.",pti2:"Sabes que el contenido importa pero no tienes tiempo para hacerlo tú mismo.",pti3:"Quieres dejar de improvisar y tener un plan real para tus redes.",pti4:"Buscas a alguien que entienda tu visión y se encargue de todo — no solo que publique.",pti5:"Quieres que más personas encuentren tu empresa a través de publicidad en Meta y Google.",pti6:"Estás en Miami y quieres trabajar con alguien que hable tu idioma.",
abTag:"SOBRE LUMMA",abSub:"ESTUDIO CREATIVO · MIAMI, FL",ab1:"Lumma nació de una convicción: todo proyecto — sin importar su tamaño — merece contenido que lo represente con orgullo.",ab2:"Con más de 10 años de experiencia en marketing, producción audiovisual y estrategia digital, acompañamos a marcas a encontrar su voz, contar su historia y conectar con las personas correctas.",ab3:"Cada proyecto es un trabajo en equipo. Tú traes la visión y la pasión por lo que haces. Juntos le damos forma, estética y estrategia para que el mundo lo vea como merece.",abQ1:"La luz ya está en tu marca.",abQ2:"Vamos a encenderla.",
faqTag:"PREGUNTAS FRECUENTES",faqH:"Lo que probablemente te estás",faqHi:"preguntando",
fq1q:"¿Qué tipo de contenido producen?",fq1a:"Principalmente video corto (Reels, TikToks, Shorts) y fotografía. Todo se produce en un content day mensual con dirección creativa y guión.",fq2q:"¿Con qué redes sociales trabajan?",fq2a:"Eso lo definimos juntos en la estrategia inicial según dónde está tu audiencia y qué hace más sentido para tu proyecto.",fq3q:"¿Cuánto tiempo toma ver resultados?",fq3a:"Los primeros 30 días son de construcción de base. Entre el mes 2 y 3 empiezas a ver tracción real.",fq4q:"¿Cómo funciona el content day?",fq4a:"Es un día coordinado donde grabamos y fotografiamos todo el contenido del mes. Tú solo te presentas — nosotros nos encargamos de todo.",fq5q:"¿Cómo funciona la publicidad digital?",fq5a:"Diseñamos la estrategia, configuramos campañas, producimos creativos y optimizamos con datos. La pauta la pagas directo a Meta o Google.",fq6q:"¿Puedo contratar solo un servicio?",fq6a:"Sí. Cada servicio funciona de manera independiente.",fq7q:"¿Necesito tener logo antes de empezar?",fq7a:"No necesariamente. Podemos empezar con social media mientras trabajamos tu branding en paralelo.",
endH:"Lo que haces merece",endHi:"brillar.",endP:"El primer paso es una conversación. Cuéntanos sobre tu proyecto y veamos juntos cómo darle la presencia digital que se merece.",
formT:"Cuéntanos sobre tu",formTi:"proyecto",formSub:"Te contactamos en menos de 24 horas.",formDone:"¡Recibido! ✦",formDoneP:"Te contactamos pronto. Síguenos en"},
en:{nav:"Let's talk",tag:"CREATIVE STUDIO · MIAMI",h1a:"Your brand has an",h1b:"incredible story.",h1c:"Let's",h1d:"tell it.",sub:"Content with intention, strategy, and aesthetics for brands that want to connect. Social media, digital advertising, and branding — all from Miami.",cta:"Book a call →",disc:"No commitment. Just a conversation.",s1:"+10",s1l:"years of experience",s2:"3",s2l:"integrated services",s3:"∞",s3l:"commitment to your brand",
imgTag:"IMAGINE THIS ✦",img1:"Your feed looks professional, cohesive, and full of personality from the first scroll.",img2:"Every piece of content tells a story — and people stop to watch.",img3:"Your clients say: \"I found you on social media and knew you were the one.\"",img4:"You don't have to think about what to post each week. It's already handled.",img5:"Your digital presence finally reflects the quality of what you do.",
svcTag:"WHAT WE DO",svcH:"Three ways to make",svcHi:"shine",svcH2:"what you do",
sm:"Social Media",smD:"Content that connects, backed by strategy.",smP:"We create and manage your social media content from start to finish. From strategy to publishing — with professional production and creative direction.",smI:"Strategy · Editorial calendar · Content day · Creative direction · Scripting · Editing · Management · Publishing · Monthly report",smFrom:"FROM",perMo:"/mo",
ad:"Digital Advertising",adD:"Your investment, working with strategy.",adP:"We manage and optimize your campaigns on Meta and Google so every dollar invested delivers real results. Strategy, technical setup, creatives, and data-driven optimization.",adI:"Strategy · Technical setup · Pixel & events · Creatives · Management · Optimization · Report & analysis",adN1:"Up to $2,000 ad spend",adN2:"$2,000+ ad spend",adOfSpend:"of ad spend",adNote:"Ad spend is paid directly to the platform.",
br:"Branding",brD:"The foundation of everything.",brP:"We build the visual and verbal identity of your brand. From logo to tone of voice — designed so you're recognized, remembered, and trusted from the first touchpoint.",brI:"Brand strategy · Logo · Visual identity · Palette · Typography · Tone of voice · Brand guide · Social media profiles",
procTag:"THE PATH TOGETHER",procH:"4 steps to",procHi:"ignite",procH2:"what you're building",p1:"We talk",p1d:"You share your vision. We understand what you do, your audience, and your goals.",p2:"We design together",p2d:"We co-create the strategy and content plan aligned to your objectives.",p3:"We produce",p3d:"A full production day where we shoot and photograph all the month's content.",p4:"We manage & measure",p4d:"We edit, publish, manage your channels, and deliver a monthly performance report.",
ptiTag:"THIS IS FOR YOU IF... ✦",pti1:"You have a running project and want your digital presence to match its quality.",pti2:"You know content matters but don't have the time to do it yourself.",pti3:"You want to stop improvising and have a real plan for your channels.",pti4:"You're looking for someone who gets your vision and handles everything — not just posts.",pti5:"You want more people to find your business through advertising on Meta and Google.",pti6:"You're in Miami and want to work with someone who speaks your language.",
abTag:"ABOUT LUMMA",abSub:"CREATIVE STUDIO · MIAMI, FL",ab1:"Lumma was born from a conviction: every project — no matter its size — deserves content that represents it with pride.",ab2:"With 10+ years of experience in marketing, video production, and digital strategy, we help brands find their voice, tell their story, and connect with the right people.",ab3:"Every project is teamwork. You bring the vision and passion for what you do. Together we shape it with aesthetics, strategy, and purpose.",abQ1:"The light is already in your brand.",abQ2:"Let's turn it on.",
faqTag:"FAQ",faqH:"What you're probably",faqHi:"wondering",
fq1q:"What type of content do you produce?",fq1a:"Mainly short-form video (Reels, TikToks, Shorts) and photography. Everything is produced in a monthly content day with creative direction and scripting.",fq2q:"Which social media platforms do you work with?",fq2a:"We define that together during the initial strategy based on where your audience is and what makes sense for your project.",fq3q:"How long does it take to see results?",fq3a:"The first 30 days are about building the foundation. Between months 2 and 3 you start seeing real traction.",fq4q:"How does the content day work?",fq4a:"It's a coordinated day where we shoot and photograph all the month's content. You just show up — we handle everything.",fq5q:"How does digital advertising work?",fq5a:"We design the strategy, set up campaigns, produce creatives, and optimize with data. You pay the ad spend directly to Meta or Google.",fq6q:"Can I hire just one service?",fq6a:"Yes. Each service works independently.",fq7q:"Do I need a logo before starting?",fq7a:"Not necessarily. We can start with social media while working on your branding in parallel.",
endH:"What you do deserves to",endHi:"shine.",endP:"The first step is a conversation. Tell us about your project and let's see how to give it the digital presence it deserves.",
formT:"Tell us about your",formTi:"project",formSub:"We'll get back to you within 24 hours.",formDone:"Received! ✦",formDoneP:"We'll be in touch soon. Follow us at"}};

function LogoFull({dark}){const fg=dark?C.dk:C.white;const dot=dark?C.cream:C.bg;return(<svg width={130} height={28} viewBox="0 0 320 60"><circle cx="20" cy="30" r="13" fill={C.green}/><circle cx="42" cy="30" r="13" fill={C.pink}/><circle cx="31" cy="30" r="5.5" fill={dot}/><text x="72" y="44" fontFamily="'Plus Jakarta Sans',sans-serif" fontSize="42" fontWeight="700" letterSpacing="6" fill={fg}>LUMMA</text></svg>);}
function FadeIn({children,delay=0}){const ref=useRef(null);const[v,setV]=useState(false);useEffect(()=>{const obs=new IntersectionObserver(([e])=>{if(e.isIntersecting)setV(true)},{threshold:0.1});if(ref.current)obs.observe(ref.current);return()=>obs.disconnect();},[]);return(<div ref={ref} className="transition-all duration-700" style={{opacity:v?1:0,transform:v?"translateY(0)":"translateY(16px)",transitionDelay:`${delay}ms`}}>{children}</div>);}
function S({children,color=C.green}){return <span style={{fontFamily:"'Instrument Serif',serif",fontStyle:"italic",fontWeight:400,color}}>{children}</span>;}
function Bdg({children,bg=C.green,color=C.bg}){return <span className="inline-block text-xs font-bold tracking-widest px-3 py-1.5 rounded-md" style={{backgroundColor:bg,color}}>{children}</span>;}
function Ico({emoji,bg=`${C.green}12`}){return(<div className="w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0" style={{backgroundColor:bg}}><span className="text-lg">{emoji}</span></div>);}
function Photo({src,alt="",aspect="1/1"}){return(<div className="rounded-xl overflow-hidden" style={{aspectRatio:aspect}}><img src={src} alt={alt} style={{width:"100%",height:"100%",objectFit:"cover",display:"block"}} /></div>);}
function Btn({onClick,children}){return(<button onClick={onClick} className="w-full py-3.5 rounded-xl text-sm font-bold active:scale-95 transition-transform" style={{backgroundColor:C.dk,color:C.green}}>{children}</button>);}

function FormModal({open,onClose,t}){const formRef=useRef(null);
useEffect(()=>{if(open&&formRef.current){formRef.current.innerHTML='';const div=document.createElement('div');div.className='hs-form-frame';div.setAttribute('data-region','na2');div.setAttribute('data-form-id','4b444e76-b047-42e6-aef1-fa2b90695a9b');div.setAttribute('data-portal-id','246101311');formRef.current.appendChild(div);if(window.hsFormEmbed){window.hsFormEmbed();}else{const check=setInterval(()=>{if(window.hsFormEmbed){window.hsFormEmbed();clearInterval(check);}},200);setTimeout(()=>clearInterval(check),5000);}}},[open]);
if(!open)return null;return(
<div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center" style={{backgroundColor:"rgba(0,0,0,0.7)"}} onClick={onClose}>
<div className="w-full max-w-md rounded-t-2xl sm:rounded-2xl overflow-y-auto" style={{backgroundColor:C.creamLight,maxHeight:"90vh"}} onClick={e=>e.stopPropagation()}>
<div className="p-6">
<div className="flex items-center justify-between mb-4"><div><p className="text-lg font-bold" style={{color:C.dk}}>{t.formT} <S color={C.pink}>{t.formTi}</S></p><p className="text-xs mt-1" style={{color:C.soft}}>{t.formSub}</p></div><button onClick={onClose} className="text-lg" style={{color:"#bbb"}}>✕</button></div>
<div ref={formRef} style={{minHeight:200}}></div>
</div></div></div>);}

export default function LummaLP(){
const[formOpen,setFormOpen]=useState(false);
const[lang,setLang]=useState("es");
useEffect(()=>{if(typeof navigator!=="undefined"&&navigator.language?.startsWith("en"))setLang("en");},[]);
const t=T[lang];const go=()=>setFormOpen(true);const otherLang=lang==="es"?"EN":"ES";

return(<><link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700;800&family=Instrument+Serif:ital@0;1&display=swap" rel="stylesheet"/>
<FormModal open={formOpen} onClose={()=>setFormOpen(false)} t={t}/>
<div style={{fontFamily:"'Plus Jakarta Sans',sans-serif"}}>

<nav className="flex items-center justify-between px-5 py-3.5" style={{backgroundColor:C.cream,position:"sticky",top:0,zIndex:40,borderBottom:"1px solid #e8e0d3"}}>
<LogoFull dark/>
<div className="flex items-center gap-2">
<button onClick={()=>setLang(lang==="es"?"en":"es")} className="text-xs font-bold px-3 py-1.5 rounded-full" style={{backgroundColor:"#e8e0d3",color:C.dk}}>{otherLang}</button>
<button onClick={go} className="text-xs font-bold px-4 py-2 rounded-full" style={{backgroundColor:C.dk,color:C.green}}>{t.nav}</button>
</div></nav>

<section className="px-5 pt-14 pb-10" style={{backgroundColor:C.cream}}>
<FadeIn><p className="text-xs tracking-widest mb-5 font-bold" style={{color:C.pink}}>{t.tag}</p>
<h1 className="text-4xl font-extrabold leading-tight mb-2" style={{color:C.dk}}>{t.h1a}</h1>
<h1 className="text-4xl leading-tight mb-2"><S color={C.pink}>{t.h1b}</S></h1>
<h1 className="text-4xl font-extrabold leading-tight" style={{color:C.dk}}>{t.h1c} <S color={C.pinkPastel}>{t.h1d}</S></h1></FadeIn>
<FadeIn delay={100}><p className="text-sm leading-relaxed mt-6 mb-8" style={{color:C.soft}}>{t.sub}</p></FadeIn>
<FadeIn delay={200}><Photo src="/images/hero.jpg" alt="Content day" aspect="4/5"/></FadeIn>
<FadeIn delay={300}><div className="mt-6"><Btn onClick={go}>{t.cta}</Btn></div><p className="text-xs text-center mt-2" style={{color:C.gray}}>{t.disc}</p></FadeIn>
</section>

<section className="px-5 py-6" style={{backgroundColor:C.dk}}><div className="flex justify-around text-center">{[{n:t.s1,l:t.s1l},{n:t.s2,l:t.s2l},{n:t.s3,l:t.s3l}].map((s,i)=>(<div key={i}><p className="text-xl font-extrabold" style={{color:C.green}}>{s.n}</p><p className="text-xs mt-0.5" style={{color:C.textLight}}>{s.l}</p></div>))}</div></section>

<section className="px-5 py-10" style={{backgroundColor:C.cream}}><FadeIn><div className="grid grid-cols-2 gap-2 mb-2"><Photo src="/images/gallery1.jpg" alt="Content day" aspect="3/4"/><Photo src="/images/gallery2.jpg" alt="Filming" aspect="3/4"/></div><div className="grid grid-cols-3 gap-2"><Photo src="/images/gallery3.jpg" alt="Editing"/><Photo src="/images/gallery4.jpg" alt="Production"/><Photo src="/images/gallery5.jpg" alt="Content"/></div></FadeIn></section>

<section className="px-5 py-14" style={{backgroundColor:C.creamLight}}><FadeIn><Bdg bg={C.pink} color={C.white}>{t.imgTag}</Bdg><div className="space-y-3 mt-6">{[t.img1,t.img2,t.img3,t.img4,t.img5].map((x,i)=>(<div key={i} className="flex gap-3 items-start p-3.5 rounded-xl" style={{backgroundColor:C.cream}}><span className="flex-shrink-0 text-sm" style={{color:C.pink}}>✦</span><p className="text-sm leading-relaxed" style={{color:C.mid}}>{x}</p></div>))}</div></FadeIn></section>

<section className="px-5 py-14" style={{backgroundColor:C.cream}}><FadeIn><Bdg>{t.svcTag}</Bdg><h2 className="text-2xl font-bold mt-4 mb-8" style={{color:C.dk}}>{t.svcH} <S color={C.pink}>{t.svcHi}</S> {t.svcH2}</h2></FadeIn>

<FadeIn><div className="rounded-2xl overflow-hidden mb-5" style={{backgroundColor:C.white,border:"1px solid #e8e0d3"}}><div className="h-1.5 w-full" style={{backgroundColor:C.green}}/><div className="p-5"><div className="flex items-center gap-3 mb-3"><Ico emoji="📱"/><div><p className="text-base font-bold" style={{color:C.dk}}>{t.sm}</p><p className="text-xs" style={{color:C.pink,fontWeight:600}}>{t.smD}</p></div></div><p className="text-sm leading-relaxed mb-4" style={{color:C.soft}}>{t.smP}</p><Photo src="/images/service-sm.jpg" alt="Social media production" aspect="16/10"/><p className="text-xs mt-4 mb-3" style={{color:C.dim}}>{t.smI}</p><div className="p-4 rounded-xl text-center" style={{backgroundColor:C.dk}}><p className="text-xs" style={{color:C.green,fontWeight:700}}>{t.smFrom}</p><p className="text-3xl font-extrabold" style={{color:C.white}}>$550</p><p className="text-xs" style={{color:C.gray}}>{t.perMo}</p></div></div></div></FadeIn>

<FadeIn><div className="rounded-2xl overflow-hidden mb-5" style={{backgroundColor:C.white,border:"1px solid #e8e0d3"}}><div className="h-1.5 w-full" style={{backgroundColor:C.pinkPastel}}/><div className="p-5"><div className="flex items-center gap-3 mb-3"><Ico emoji="⚡" bg={`${C.pinkPastel}15`}/><div><p className="text-base font-bold" style={{color:C.dk}}>{t.ad}</p><p className="text-xs" style={{color:C.pinkPastel,fontWeight:600}}>{t.adD}</p></div></div><p className="text-sm leading-relaxed mb-4" style={{color:C.soft}}>{t.adP}</p><p className="text-xs mb-4" style={{color:C.dim}}>{t.adI}</p><div className="flex gap-3"><div className="flex-1 p-3 rounded-xl text-center" style={{backgroundColor:C.dk}}><p className="text-xl font-extrabold" style={{color:C.white}}>$250</p><p className="text-xs" style={{color:C.gray}}>{t.perMo}</p><p className="text-xs mt-1" style={{color:C.pinkPastel}}>{t.adN1}</p></div><div className="flex-1 p-3 rounded-xl text-center" style={{backgroundColor:C.dk}}><p className="text-xl font-extrabold" style={{color:C.white}}>15%</p><p className="text-xs" style={{color:C.gray}}>{t.adOfSpend}</p><p className="text-xs mt-1" style={{color:C.pinkPastel}}>{t.adN2}</p></div></div><p className="text-xs text-center mt-2" style={{color:C.dim}}>{t.adNote}</p></div></div></FadeIn>

<FadeIn><div className="rounded-2xl overflow-hidden" style={{backgroundColor:C.white,border:"1px solid #e8e0d3"}}><div className="h-1.5 w-full" style={{background:`linear-gradient(90deg,${C.green},${C.pink})`}}/><div className="p-5"><div className="flex items-center gap-3 mb-3"><Ico emoji="✦"/><div><p className="text-base font-bold" style={{color:C.dk}}>{t.br}</p><p className="text-xs" style={{color:C.pink,fontWeight:600}}>{t.brD}</p></div></div><p className="text-sm leading-relaxed mb-4" style={{color:C.soft}}>{t.brP}</p><p className="text-xs mb-4" style={{color:C.dim}}>{t.brI}</p><div className="p-4 rounded-xl text-center" style={{backgroundColor:C.dk}}><p className="text-3xl font-extrabold" style={{color:C.white}}>$350</p></div></div></div></FadeIn>

<FadeIn><div className="mt-8"><Btn onClick={go}>{t.cta}</Btn></div></FadeIn></section>

<section className="px-5 py-14" style={{backgroundColor:C.creamLight}}><FadeIn><Bdg>{t.procTag}</Bdg><h2 className="text-2xl font-bold mt-4 mb-8" style={{color:C.dk}}>{t.procH} <S color={C.pink}>{t.procHi}</S> {t.procH2}</h2></FadeIn>
{[{n:"01",t2:t.p1,d:t.p1d,c:C.green},{n:"02",t2:t.p2,d:t.p2d,c:C.pinkPastel},{n:"03",t2:t.p3,d:t.p3d,c:C.green},{n:"04",t2:t.p4,d:t.p4d,c:C.pinkPastel}].map((s,i)=>(<FadeIn key={s.n} delay={i*80}><div className="flex gap-4 items-start p-4 rounded-xl mb-3" style={{backgroundColor:C.white}}><div className="w-11 h-11 rounded-xl flex items-center justify-center flex-shrink-0" style={{backgroundColor:s.c}}><span className="text-sm font-extrabold" style={{color:C.dk}}>{s.n}</span></div><div><p className="text-sm font-bold mb-1" style={{color:C.dk}}>{s.t2}</p><p className="text-xs leading-relaxed" style={{color:C.soft}}>{s.d}</p></div></div></FadeIn>))}</section>

<div className="py-6 text-center" style={{backgroundColor:C.dk}}><button onClick={go} className="text-sm font-bold px-8 py-3 rounded-xl active:scale-95 transition-transform" style={{backgroundColor:C.green,color:C.dk}}>{t.cta}</button></div>

<section className="px-5 py-14" style={{backgroundColor:C.cream}}><FadeIn><Bdg bg={C.pink} color={C.white}>{t.ptiTag}</Bdg><div className="space-y-3 mt-6">{[t.pti1,t.pti2,t.pti3,t.pti4,t.pti5,t.pti6].map((x,i)=>(<div key={i} className="flex gap-3 items-start p-3.5 rounded-xl" style={{backgroundColor:C.creamLight}}><span className="flex-shrink-0 text-xs font-bold" style={{color:C.pink}}>✓</span><p className="text-sm leading-relaxed" style={{color:C.mid}}>{x}</p></div>))}</div></FadeIn></section>

<section className="px-5 py-14" style={{backgroundColor:C.warm}}><FadeIn><p className="text-xs tracking-widest mb-2" style={{color:C.pinkPastel}}>{t.abTag}</p><p className="text-xs tracking-widest mb-6" style={{color:C.green}}>{t.abSub}</p><p className="text-sm leading-relaxed mb-4" style={{color:C.textLight}}>{t.ab1}</p><p className="text-sm leading-relaxed mb-4" style={{color:C.textLight}}>{t.ab2}</p><p className="text-sm leading-relaxed mb-6" style={{color:C.textLight}}>{t.ab3}</p><Photo src="/images/about.jpg" alt="Lumma Studio" aspect="16/10"/></FadeIn>
<FadeIn delay={100}><div className="p-5 rounded-xl mt-6" style={{backgroundColor:C.bg,borderLeft:`3px solid ${C.green}`}}><p className="text-lg font-bold leading-snug" style={{color:C.white}}>{t.abQ1}</p><p className="text-lg font-bold leading-snug"><S>{t.abQ2}</S></p></div></FadeIn></section>

<section className="px-5 py-14" style={{backgroundColor:C.creamLight}}><FadeIn><Bdg bg={C.pink} color={C.white}>{t.faqTag}</Bdg><h2 className="text-xl font-bold mt-4 mb-6" style={{color:C.dk}}>{t.faqH} <S color={C.pink}>{t.faqHi}</S></h2><div className="space-y-3">{[{q:t.fq1q,a:t.fq1a},{q:t.fq2q,a:t.fq2a},{q:t.fq3q,a:t.fq3a},{q:t.fq4q,a:t.fq4a},{q:t.fq5q,a:t.fq5a},{q:t.fq6q,a:t.fq6a},{q:t.fq7q,a:t.fq7a}].map((f,i)=>(<div key={i} className="p-4 rounded-xl" style={{backgroundColor:C.cream}}><p className="text-sm font-bold mb-1" style={{color:C.dk}}>{f.q}</p><p className="text-xs leading-relaxed" style={{color:C.soft}}>{f.a}</p></div>))}</div></FadeIn></section>

<section className="px-5 py-16 relative" style={{backgroundColor:C.bg}}><div className="absolute inset-0" style={{background:`radial-gradient(ellipse at 40% 40%,${C.green}06 0%,transparent 50%),radial-gradient(ellipse at 70% 70%,${C.pink}05 0%,transparent 50%)`}}/><div className="relative z-10 text-center"><FadeIn><svg width={50} height={34} viewBox="0 0 60 60" className="mx-auto mb-5"><circle cx="22" cy="30" r="14" fill={C.green}/><circle cx="38" cy="30" r="14" fill={C.pink}/><circle cx="30" cy="30" r="6" fill={C.bg}/></svg><h2 className="text-2xl font-bold mb-2" style={{color:C.white}}>{t.endH} <S>{t.endHi}</S></h2><p className="text-sm mb-6" style={{color:C.textLight}}>{t.endP}</p><button onClick={go} className="w-full py-3.5 rounded-xl text-sm font-bold active:scale-95 transition-transform" style={{backgroundColor:C.green,color:C.bg}}>{t.cta}</button><p className="text-xs mt-4" style={{color:C.dim}}>sonia@lummacreative.com · @lummastudio_</p></FadeIn></div></section>

<footer className="px-5 py-8 text-center" style={{backgroundColor:C.bg,borderTop:`1px solid ${C.dimmer}`}}><LogoFull/><p className="text-xs mt-3" style={{color:C.dim}}>Miami, FL · sonia@lummacreative.com</p><div className="flex justify-center gap-4 mt-3"><span className="text-xs" style={{color:C.gray}}>Instagram</span><span className="text-xs" style={{color:C.gray}}>WhatsApp</span><span className="text-xs" style={{color:C.gray}}>Email</span></div><p className="text-xs mt-4" style={{color:C.dim}}>© 2026 Lumma Studio.</p></footer>
</div></>);}
